name: Build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install -f TestSonarqubeRepoCode/pom.xml
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
            projectBaseDir: .
            args: >
              -Dsonar.organization=virendasainitestrepo
              -Dsonar.projectKey=virendasainitestrepo_TestSonarqubeRepoCode_cbbe886f-63a7-4f48-bd22-814ac057382c
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
